# Generated by Django 4.1.5 on 2023-03-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
