# Generated by Django 4.1 on 2023-03-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='tombstone',
            field=models.BooleanField(default=False),
        ),
    ]
