# Generated by Django 3.2.7 on 2023-04-26 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOUIAccount',
            fields=[
                ('kode_identitas', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=1024)),
                ('kode_organisasi', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=1024, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Staff Keuangan', 'Staff Keuangan'), ('Guest', 'Guest')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
