# Generated by Django 4.1 on 2023-05-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='terms',
            field=models.CharField(default='(GASAL-XXXX/XXXX)', max_length=50),
        ),
    ]
