# Generated by Django 4.1 on 2023-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='terms',
            field=models.CharField(default='GASAL-XXXX/XXXX', max_length=50),
        ),
    ]
