# Generated by Django 4.1 on 2023-04-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_tax_eventemployee_honor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemployee',
            name='netto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
