# Generated by Django 3.2.7 on 2023-04-26 04:43

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('OTP', models.IntegerField()),
                ('valid_until', models.DateTimeField(blank=True, default=authentication.models.now_plus_10_minutes)),
                ('is_redeem', models.BooleanField(default=False)),
                ('is_changed', models.BooleanField(default=False)),
            ],
        ),
    ]
