# Generated by Django 4.1.5 on 2023-03-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordotp',
            name='OTP',
            field=models.IntegerField(),
        ),
    ]
